### ISSUE TITLE
[Conflict issue] Still not compatible with 3rdPerson mods, i think this mod changed layer about the render

### ISSUE THREAD

**Issue by CoolLKKPS** [cmooref17/Lethal-Company-TooManyEmotes#76] opened 2024-02-22 12:19 UTC
maybe that's the things u break?

**Comment by ajsglist** [comment] 2024-02-25 02:46
verity's 3rd person mod hasn't been updated in 2.5 months and has a bunch of issues with different mods... unless you can point out a specific issue you believe is caused by TME, this issue report is deeply unhelpful and not something that can realistically be acted upon

**Comment by CoolLKKPS** [comment] 2024-02-25 03:22
@ajsglist ok uh but idk, what 3rd person mod can replace that mod?

**Comment by cmooref17** [comment] 2024-02-25 04:51
What part isn't compatible anyways?

**Comment by ajsglist** [comment] 2024-02-25 04:54
> @ajsglist ok uh but idk, what 3rd person mod can replace that mod?

None of them are particularly bug-free or well-maintained to my knowledge

Regardless, nowhere in your reported "issue" is a bug report for Too Many Emotes.  If you don't have a specific bug report for the developer of *this* mod, please consider respecting their time and closing this ticket.

**Comment by CoolLKKPS** [comment] 2024-02-25 04:54
uh model not display... ? u can simply test that

**Comment by ajsglist** [comment] 2024-02-25 04:56
> uh model not display... ? u can simply test that

In order for them to test something you'd need to articulate a bug and the reproducibility conditions, which up to this point you refused to do.

Please endeavor to provide actionable information, specifically regarding what is broken in *this* mod.  Otherwise please consider closing this ticket and directing your concerns to the mod that's actually broken.

**Comment by CoolLKKPS** [comment] 2024-02-25 04:57
@ajsglist So what u're doing right now, is i shouldn't report any issues IF i got issues

**Comment by CoolLKKPS** [comment] 2024-02-25 05:02
u know what, if they don't care this issues, they can just simply ignore just like most devs doing, bc they don't value my feedback, maybe that's my problem, but at least im not trying to force every devs to do something, think about that, i also can send this feedback to 3rdperson mod, if i can contact that dev, but the thing is, if this issue is not from 3rdperson?

**Comment by CoolLKKPS** [comment] 2024-02-25 05:07
and ok, i don't really think this issue is important, already have so many people report this issue, i should bump issue instead create another issue, so that issue will be there more longer

**Comment by cmooref17** [comment] 2024-02-25 05:38
This used to be compatible with third person mods. I'd have to take a look and see why.

**Comment by CoolLKKPS** [comment] 2024-02-25 11:47
@cmooref17 will send a video for u, hang on
pretty sure u changed the logical about 3rd person view cam for cosmetics and ghost girl, maybe u can made a 3rd person API to let other people base on that API to made 3rd person

**Comment by CoolLKKPS** [comment] 2024-02-25 12:04
if use3rdperson and withTME then
  print("cannot move the cam while emote")
  print("emote wheel ui malfunction")
end


https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/96377775/35a15748-11a2-42ac-ae82-322dfa27b380

**Comment by CoolLKKPS** [comment] 2024-02-25 12:10
pretty sure that's bc u changed the layout about render layer, but other mod didn't, that made some conflict, and that's why i sug made a API mod or/and hopefully u can made a 3rdperson mod
still good to see u still active, if i can able to do that, i may have to buy a coffee for u

**Comment by CoolLKKPS** [comment] 2024-03-02 13:11
this issue are also send to MoreCompany, to see if have any solution

**Closed** 2024-03-19 03:11 UTC

**Comment by CoolLKKPS** [comment] 2024-03-19 03:52
this issue are not got fix even any, but will close to let other issue ticket handle
