### ISSUE TITLE
(Compatibility Issue) toomanyemotesscraps messes with the weight of lategameupgrades's shopping kart.

### ISSUE THREAD

**Issue by TheComicRelief** [cmooref17/Lethal-Company-TooManyEmotes#114] opened 2024-04-16 14:16 UTC
When i put the junk food scrap into the shopping kart, the weight of the kart goes to being 0 lbs. I have tested with both vanilla scrap & other mod scrap and this is the only one causing it.

**Comment by cmooref17** [comment] 2024-04-16 16:17
What mod is the shopping cart from?
Also, have you tried with other emote props? Such as the baseball bat, sexy saxophone, trombone, etc?

Maybe the issue is because the junk food has a weight of zero. In the vanilla code, it's possible that 1 is the lowest weight, but they clamp the values so it doesn't matter. Maybe the zero is causing issues.

I could look into it.

**Comment by cmooref17** [comment] 2024-04-16 19:26
Okay, I pushed a fix for this now. I checked, and it looked like LGU wasn't clamping the weight value, which was making it add a negative number, because the weight it adds is weight - 1, which was -1, but I made the items minimum weight 1 now, since this is how it should have been done anyways. Thanks for letting me know about this!

**Closed by cmooref17** 2024-04-16 19:26 UTC
