### ISSUE TITLE
Since Update 2.1.20 and onwards, VRM model conflict

### ISSUE THREAD

**Issue by zalkyria** [cmooref17/Lethal-Company-TooManyEmotes#148] opened 2024-08-05 16:45 UTC
I'm not sure what exactly changed between versions 2.1.19 to 2.1.20, I saw you fixed the third person camera, but when using lethal vrm or better vrm mods where they both worked previously with ver 2.1.19 and I could see the character just fine, now they outright are invisible. I've included what it looks like with the third person mode.
![image](https://github.com/user-attachments/assets/baf0b651-4a7a-4e53-9da2-2a85410747e7)

**Comment by zalkyria** [comment] 2024-08-05 17:12
I've tested it seperately with only toomanyemotes and either bettervrm or lethal vrm, and the issue still happens, so I know its not a mod conflict with other mods except for this :( I just want to see my 3d model emote with your mod again T^T

I will say I can still see my friends emote with it just fine and I can see them dance, but when we emote and enter third person can't see ourselves emote just whatever accessory we have on our model.

01912386-03a0-ec1e-7b42-904baba9bebe - this is the profile code that is just better vrm, too many emotes, and bepin

**Comment by SelwynCoy** [comment] 2024-08-25 04:51
Reproduced this issue with my group; emote wheel shows the default Lethal Company model, but when performing the emote you will be invisible in the third-person view. Other players will see you just fine, but you will not be able to see yourself. I tried rolling back to older versions and encountered the same issue, except in the older versions our models were also invisible in the emote wheel.

**Comment by zalkyria** [comment] 2024-08-25 05:01
Yeah that's what I thought idk if it's something that can be fixed thank you for checking it out. Maybe one day but at least we can still see each other's models with it just not our own in 3rd person. I did consider just using the first person mode if I don't want to see my invisible self.

**Comment by cmooref17** [comment] 2024-08-25 07:44
I looked into this, but it looks like the mod renders their models on layer 23, and for various reasons, I don't render the third person emotes on that layer anymore.

I tried to see if I could change the layer of the vrm models, but the mod seems to change it back to layer 23 immediately unfortunately. 

I could probably make a makeshift exception when this mod is enabled, to allow the emote camera to also view layer 23, but considering some mods use this layer to hide things that are not supposed to be seen, there may be uncommon visual issues with some mod combinations. I don't think this part will be that big of an issue, though.

**Comment by cmooref17** [comment] 2024-08-25 21:38
Could anyone verify for me if this seems to be working on the latest version?

**Comment by zalkyria** [comment] 2024-08-25 23:56
It works! Thank you so much 🥹💖

**Comment by cmooref17** [comment] 2024-08-26 01:24
You're welcome!

**Closed by cmooref17** 2024-08-26 01:24 UTC
